# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
    - main

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3     

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: get Flex theme
      run: |
        mkdir -p ../pelican-themes/
        rm -rf ../pelican-themes/*
        git clone -b v2.5.0 --single-branch --depth=1 https://github.com/alexandrevicenzi/Flex.git ../pelican-themes/Flex

    - name: build site
      run: make publish

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
